Fix `jvm_export` with no sources
Previously, `jvm_export` rules with no sources (eg. a library that
serves as an umbrella for several libraries) would fail during
analysis with the following error:

```
ERROR: /Users/me/work/lib/BUILD:60:14: in jvm_export rule //lib:lib.publish:
Traceback (most recent call last):
        File "(...)/jvm_export/jvm_export.bzl", line 43, column 37, in _jvm_export_impl
                source_jar = _source_jar(artifact)
        File "(...)/jvm_export/jvm_export.bzl", line 159, column 44, in _source_jar
                return target[JavaInfo].source_jars[0]
Error: index out of range (index is 0, but sequence has 0 elements)
```

With this patch, the rule will no longer try to find a sources jar that
doesn't exist.